### ISSUE TITLE
Checklist for Monday, Going to Production

### ISSUE THREAD

**Issue by Gregg** [Code-Pop/vue-mastery#169]
To do on Monday morning:
- [ ] Add missing future lessons for Advanced Component course from staging db to production db @gregg 
- [ ] Deploy

To fully test:
- [ ] Test account Stripe payment
- [ ] Test account paypal payment 
- [ ] Test team payments

After things look like they're working:
- [ ] Signup for profitwell

**Comment by pieer** [comment]
Very old issue
